#pragma once

#include <algorithm>
#include <sstream>
#include <set>
#include <deque>
#include <fstream>
#include <cassert>
#include <string>

#pragma warning(push, 3)
#include <QGridLayout>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QLabel>
#include <QGraphicsRectItem>
#include <QHBoxLayout>
#include <QButtonGroup>
#include <QToolButton>
#include <QStringList>
#include <QKeyEvent>
#include <QCompleter> 
#include <QColor>
#include <QtGui>
#include <QPolygonF>
#include <QLine>
#include <QGraphicsSceneContextMenuEvent>
#include <QTableWidget>
#include <QHeaderView>
#include <QLayout>
#include <QScrollBar>
#include <QFontMetrics>
#include <QTableWidgetItem>
#include <QLineEdit>
#include <QMenu>
#include <QGraphicsSceneMouseEvent>
#include <QPen>
#include <QAction>
#include <QTimer>
#include <QBrush>
#include <QColor>
#include <QTextOption>
#include <QTextItem>
#include <QList>
#include <QMessageBox>
#pragma warning(pop)